azure:
  activedirectory:
    tenant-id: <tenant-id>
    client-id: <client-id>
    client-secret: <client-secret>
    authorization:
      graph:
        scope:
          - "Calendars.Read"
      arm:
        scope:
          - "https://management.core.windows.net/user_impersonation"
server:
  port: 8080
  servlet:
    session:
      timeout: 36000000
spring:
  profiles:
    active: develop