logging:
  level:
    root: INFO
    com:
      azure:
        spring:
          aad:
            implementation: DEBUG
azure:
  activedirectory:
    tenant-id: <tenant-id>
    client-id: <client-id>
    client-secret: <client-secret>
    authorization:
      graph:
        scopes:
          - "https://graph.microsoft.com/Calendars.Read"
      arm:
        scopes:
          - "https://management.core.windows.net/user_impersonation"
    user-group:
      value: "#microsoft.graph.group"
      allowed-groups: group1, group2
server:
  port: 8080
  servlet:
    session:
      timeout: 36000000
spring:
  profiles:
    active: develop